### ISSUE TITLE
Looking for installation help

### ISSUE THREAD

**Issue by itsTripp** [JamesIves/perforce-commit-discord-bot#15]
So I'm sorry to do it like this, but I'm very unsure on what to do after getting p4 changes to work. I'm honestly not all sure what and where all these files from the git are to be located and where to install python. Do any files need to be uploaded to the perforce server for this to work? I'm also getting invalid syntax when I try to do the $ pip install -r requirements.txt and such. Took hours to get this far and I feel like I have files just lying around in places they shouldn't be.
![python error](https://user-images.githubusercontent.com/6070721/65933026-95aa0e80-e3d5-11e9-8a29-d26005c2f4e2.png)

**Comment by JamesIves** [comment]
The files need to be executed by an instance of Python you have installed on your Perforce server. The scripts make calls to the `p4 changes` command on an interval which is why `app.py` needs to be initialized somewhere you can run `p4 changes` yourself. 

The following articles may help you get started with installing Python/Pip.

* https://wiki.python.org/moin/BeginnersGuide/Download
* https://pip.pypa.io/en/stable/installing/

Unfortunately I can't offer any form of support with getting this up and running. It's not the most user friendly script in the world, and requires some prior Python/dev ops knowledge before using. Use at your own risk.
